BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[RepresentationContact] ALTER COLUMN [under18] BIT NULL;
ALTER TABLE [dbo].[RepresentationContact] ALTER COLUMN [type] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
