# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      azure:
        patterns:
          - '@azure/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      jest:
        patterns:
          - 'jest'
          - 'jest-each'
          - 'jest-environment-jsdom'
          - '@types/jest'
      opentelemetry:
        patterns:
          - '@opentelemetry/*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-*'
      prisma: # group prisma library and client updates together
        patterns:
          - 'prisma'
          - '@prisma/*'
      rollup:
        patterns:
          - '@rollup/*'
      types:
        patterns:
          - '@microsoft/microsoft-graph-types'
          - '@types/*'
  - package-ecosystem: 'terraform'
    directory: '/infrastructure' # Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'tuesday' # day after npm updates
