parameters:
- name: root
  type: string
- name: folderName
  type: string
- name: nodeVersion
  type: number
  default: 18

steps:
  - task: ArchiveFiles@2
    displayName: ${{parameters.folderName}} - archive files
    inputs:
      rootFolderOrFile: $(Build.Repository.LocalPath)/${{parameters.root}}/functions/${{parameters.folderName}}
      includeRootFolder: false
      archiveFile: $(System.DefaultWorkingDirectory)/functions.zip
  - publish: $(System.DefaultWorkingDirectory)/functions.zip
    artifact: function-${{parameters.root}}-${{parameters.folderName}}
    displayName: ${{parameters.folderName}} - publish artifact