parameters:
  - name: deployAppealsAPI
    displayName: Deploy Appeals API
    type: boolean
    default: true
  - name: deployAppealsWeb
    displayName: Deploy Appeals Web
    type: boolean
    default: true
  - name: deployFunctionAppealsCasedataImport
    displayName: Deploy Function - Appeals Casedata Import
    type: boolean
    default: true
  - name: deployFunctionAppealsUserImport
    displayName: Deploy Function - Appeals User Import
    type: boolean
    default: true
  - name: deployFunctionAppealsDocProcessing
    displayName: Deploy Function - Appeals Document Processing
    type: boolean
    default: true
  - name: region
    displayName: Region
    type: string
    values:
      - UK West
      - UK South
    default: UK West
  - name: schemaMigration
    displayName: Run Database Migration
    type: boolean
    default: true

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.4.0
  pipelines:
    - pipeline: build
      source: Back Office Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Deploy Appeals
        deploymentJobs:
          - name: Deploy Appeals API
            condition: eq(${{ parameters.deployAppealsAPI }}, 'true')
            steps:
              - ${{ if eq(parameters.schemaMigration, true) }}:
                  - checkout: self
                  - template: ../steps/azure_get_secrets.yml
                    parameters:
                      secrets:
                        - name: back-office-appeals-sql-connection-string
                          variable: DATABASE_URL
                  - template: ../steps/node_script.yml
                    parameters:
                      nodeVersion: 18
                      environmentVariables:
                        DATABASE_URL: $(DATABASE_URL)
                      script: npm run db:migrate:prod
                      workingDirectory: $(Build.Repository.LocalPath)/appeals/api
              - template: ../steps/azure_web_app_deploy.yml
                parameters:
                  appName: pins-app-back-office-appeals-api-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: back-office/back-office-appeals-api
          - name: Deploy Appeals Web
            condition: eq(${{ parameters.deployAppealsWeb }}, 'true')
            steps:
              - template: ../steps/azure_web_app_deploy.yml
                parameters:
                  appName: pins-app-back-office-appeals-wfe-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: back-office/appeals-web
          - name: Deploy Function - Appeals Casedata Import
            artifact:
              name: function-appeals-casedata-import
              sourcePipeline: Back Office Build
            condition: eq(${{ parameters.deployFunctionAppealsCasedataImport }}, 'true')
            steps:
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-bo-appeals-casedata-import-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  resourceGroup: $(resourceGroup)
          - name: Deploy Function - Appeals User Import
            artifact:
              name: function-appeals-user-import
              sourcePipeline: Back Office Build
            condition: eq(${{ parameters.deployFunctionAppealsUserImport }}, 'true')
            steps:
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-bo-appeals-user-import-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  resourceGroup: $(resourceGroup)
          - name: Deploy Function - Appeals Document Processing
            artifact:
              name: function-appeals-document-processing
              sourcePipeline: Back Office Build
            condition: eq(${{ parameters.deployFunctionAppealsDocProcessing }}, 'true')
            steps:
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-bo-appeals-doc-processing-$(ENVIRONMENT)-$(REGION_SHORT)-001
                  resourceGroup: $(resourceGroup)
    globalVariables:
      - template: azure-pipelines-variables.yml@self
