trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.2.0

parameters:
  - name: environment
    type: string
    default: dev
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
  - name: validateName
    type: string
    default: Validate

stages:
  - template: stages/wrapper_stage.yml@templates
    parameters:
      jobs:
        - job: check_branch_name
          displayName: Check branch name
          steps:
            - checkout: self
              clean: true
              persistCredentials: true
            - template: ../steps/check_branch_name.yml
            - template: ../steps/git_tagging.yml
        - job: install
          displayName: Install Dependencies
          steps:
            - checkout: self
              clean: true
              persistCredentials: true
            - template: ../steps/node_script.yml
              parameters:
                script: npm ci
            - task: ArchiveFiles@2
              displayName: "Archive Build"
              inputs:
                rootFolderOrFile: $(System.DefaultWorkingDirectory)
                archiveType: zip
                archiveFile: $(System.DefaultWorkingDirectory)/build.zip
            - publish: $(System.DefaultWorkingDirectory)/build.zip
              artifact: build
        - job: commitlint
          dependsOn: install
          displayName: Run Commitlint
          steps:
            - download: current
              artifact: build
            - task: ExtractFiles@1
              displayName: "Extract Build"
              inputs:
                archiveFilePatterns: $(System.DefaultWorkingDirectory)/build.zip
                destinationFolder: $(System.DefaultWorkingDirectory)
            - template: ../steps/node_script.yml
              parameters:
                script: run commitlint
      pool: ${{ parameters.pool }}
      name: ${{ parameters.validateName }}
      variables:
        - template: ../variables/environments/${{ lower(parameters.environment) }}.yml
