parameters:
    - name: removeAllCases
      displayName: THIS CHANGE IS NOT FOR MAIN, IT IS INTENDED TO RUN ONCE TO CLEAN UP TEST CASES ON TEST ENV FROM ANOTHER BRANCH
      type: string
      values:
          - true
          - false
    - name: specifiedCases
      displayName: Comma separated case references
      type: string
    - name: maxCasesToDelete
      displayName: Max cases to delete
      type: number
      default: 40
    - name: maxWaitInSeconds
      displayName: Max transaction wait in seconds
      type: number
      default: 20
    - name: maxTimeoutInSeconds
      displayName: Max transaction timeout in seconds
      type: number
      default: 100

pool: pins-odt-agent-pool

pr: none

trigger: none

resources:
    repositories:
        - repository: templates
          type: github
          endpoint: Planning-Inspectorate
          name: Planning-Inspectorate/common-pipeline-templates
          ref: refs/tags/release/3.16.1

variables:
    - template: variables/environments/test.yml@templates
    - group: pipeline_secrets


jobs:
    - deployment: Remove_specified_cases_from_DB
      displayName: Remove specified cases from test Database
      environment: test
      strategy:
        runOnce:
            deploy:
                steps:
                    - download: none
                    - checkout: self
                    - template: steps/node_script.yml@templates
                      parameters:
                          nodeVersion: 20
                          script: npm ci
                    - template: steps/azure_auth.yml@templates
                    - template: steps/azure_get_secrets.yml@templates
                      parameters:
                          secrets:
                              - name: back-office-sql-server-connection-string
                                variable: DATABASE_URL
                    - template: steps/node_script.yml@templates
                      parameters:
                          nodeVersion: 20
                          environmentVariables:
                              DATABASE_URL: $(DATABASE_URL)
                          script: npm run prisma-generate
                          workingDirectory: $(Build.Repository.LocalPath)/apps/api
                    - template: steps/node_script.yml@templates
                      parameters:
                          nodeVersion: 20
                          environmentVariables:
                              DATABASE_URL: $(DATABASE_URL)
                              SPECIFIED_CASES: ${{parameters.specifiedCases}}
                              REMOVE_ALL_CASES: ${{parameters.removeAllCases}}
                              MAX_CASES_TO_DELETE: ${{parameters.maxCasesToDelete}}
                              TRANSACTION_MAX_WAIT_IN_SECONDS: ${{parameters.maxWaitInSeconds}}
                              TRANSACTION_TIMEOUT_IN_SECONDS: ${{parameters.maxTimeoutInSeconds}}
                          script: npm run applications:remove-all-specified-cases
                          workingDirectory: $(Build.Repository.LocalPath)/packages/scripts
      workspace:
        clean: all

