parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
      - Dev
      - Test
      - Prod

pool: pins-odt-agent-pool

pr: none

trigger:
- none

schedules:
  - cron: "0 0 1 * *"
    displayName: MonthlyBuild
    branches:
      include:
        - main
    always: true

variables:
  - group: back-office-infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.4.0

jobs:
  - deployment: RegenerateApiKeys
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 18
                script: npm ci --workspaces=@pins/packages.scripts
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 18
                environmentVariables:
                  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
                  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
                  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
                  KEY_VAULT_NAME: $(KEY_VAULT_NAME_DEV)
                script: npm run applications:regenerate-api-keys
                workingDirectory: $(Build.Repository.LocalPath)/packages/scripts
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 18
                environmentVariables:
                  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
                  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
                  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
                  KEY_VAULT_NAME: $(KEY_VAULT_NAME_TEST)
                script: npm run applications:regenerate-api-keys
                workingDirectory: $(Build.Repository.LocalPath)/packages/scripts
            - template: steps/node_script.yml@templates
              parameters:
                nodeVersion: 18
                environmentVariables:
                  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
                  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
                  AZURE_TENANT_ID: $(AZURE_TENANT_ID)
                  KEY_VAULT_NAME: $(KEY_VAULT_NAME_PROD)
                script: npm run applications:regenerate-api-keys
                workingDirectory: $(Build.Repository.LocalPath)/packages/scripts
