parameters:
  - name: Environment
    type: string
    default: 'test'
    values:
      - 'dev'
      - 'test'

variables:
  - name: APP
    value: 'applications'
  - group: e2e-${{ parameters.Environment }}

pr: none

trigger: none

jobs:
  - job: E2E_Tests_Group_1
    timeoutInMinutes: 60
    pool: pins-odt-agent-pool-tests
    steps:
      - task: UseNode@1
        displayName: "Use Node.js 20.19.5"
        inputs:
          version: '20.19.5'

      - task: Npm@1
        inputs:
          command: "install"
          workingDir: $(System.DefaultWorkingDirectory)/apps/e2e
        displayName: "Install Dependencies"

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: npx cypress run --spec "cypress/e2e/back-office-applications/addRepresentation.spec.js"
          workingDirectory: 'apps/e2e'

        env:
          BASE_URL: $(BASE_URL)
          CASE_TEAM_EMAIL: $(CASE_TEAM_EMAIL)
          CASE_ADMIN_EMAIL: $(CASE_ADMIN_EMAIL)
          INSPECTOR_EMAIL: $(INSPECTOR_EMAIL)
          USER_PASSWORD: $(USER_PASSWORD)
          FEATURE_FLAG_CONNECTION_STRING: $(FEATURE_FLAG_CONNECTION_STRING)
        displayName: "Run Cypress Tests Group 1" 

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'apps/e2e/cypress/screenshots'
          artifactName: 'FailedTests'
        displayName: "Publish Failed Tests Artifacts"
        condition: failed()
