# Pipeline optimizations for handling memory issues and test timeouts
# Key problems being addressed:
# 1. Tests taking too long to finish
# 2. Memory exhaustion on build agents
# 3. Difficulty identifying which tests are failing
# 4. Resource contention between different test types

trigger:
    branches:
        include:
            # trigger for merge queue branches
            - gh-readonly-queue/*

pr:
    branches:
        include:
            - '*'
    paths:
        exclude:
            - infrastructure

resources:
    repositories:
        - repository: templates
          type: github
          endpoint: Planning-Inspectorate
          name: Planning-Inspectorate/common-pipeline-templates
          ref: refs/tags/release/3.17.0

extends:
    template: stages/wrapper_ci.yml@templates
    parameters:
        pool:
            name: pins-odt-agent-pool
        gitFetchDepth: 0
        globalVariables:
            - template: azure-pipelines-variables.yml@self
        validationJobs:
            - job: Setup
              displayName: Setup Environment
              steps:
                  - script: git fetch origin main:main
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm ci

            - job: Static_Analysis
              displayName: Static Analysis
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm run commitlint
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm run tscheck
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm run lint:js
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm run format-check

            - job: API_Unit_Tests
              displayName: API Unit Tests
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            cd apps/api && npm run test:light
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: API_Integration_Tests
              displayName: API Integration Tests
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            cd apps/api && npm run test:heavy
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: Web_Unit_Tests
              displayName: Web Unit Tests
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            cd apps/web && npm run test:light
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: Web_Integration_Tests
              displayName: Web Integration Tests
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            cd apps/web && npm run test:heavy
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: API_Testing
              displayName: API Testing
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            cd apps/api-testing && npm run test:ci
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: Function_Tests
              displayName: Function Tests
              dependsOn: Setup
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: |
                            export NODE_OPTIONS="--max-old-space-size=4096"
                            npx turbo run test --filter=./apps/functions/* -- --maxWorkers=2
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)

            - job: Build
              displayName: Build Release
              dependsOn:
                - Static_Analysis
                - API_Unit_Tests
                - API_Integration_Tests
                - Web_Unit_Tests
                - Web_Integration_Tests
                - API_Testing
                - Function_Tests
              steps:
                  - template: ../steps/node_script.yml
                    parameters:
                        nodeVersion: 20
                        script: npm run build:release
                        environmentVariables:
                            TURBO_TEAM: $(TURBO_TEAM)
                            TURBO_API: $(TURBO_API)
                            TURBO_TOKEN: $(TURBO_TOKEN)
