parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
      - Dev
      - Test

pool: pins-odt-agent-pool

pr: none

trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.1.1

variables:
  - template: variables/environments/${{ lower(parameters.environment )}}.yml@templates
  - group: pipeline_secrets

jobs:
  - deployment: Seed_DB
    displayName: Seed ${{ parameters.environment }} Database
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: self
            - template: steps/node_script.yml@templates
              parameters:
                script: npm ci
            - template: steps/azure_auth.yml@templates
            - template: steps/azure_get_secrets.yml@templates
              parameters:
                secrets:
                  - name: back-office-sql-connection-string
                    variable: DATABASE_URL
            - template: steps/node_script.yml@templates
              parameters:
                script: npm run build
                workingDirectory: $(Build.Repository.LocalPath)/apps/api
            - template: steps/node_script.yml@templates
              parameters:
                environmentVariables:
                  DATABASE_URL: $(DATABASE_URL)
                script: npm run db:seed
                workingDirectory: $(Build.Repository.LocalPath)/apps/api
    workspace:
      clean: all
