parameters:
  - name: environment
    type: string
    default: Dev
    values:
      - Dev
      - Test

pool: pins-odt-agent-pool

pr: none

trigger: none

variables:
  - group: key-vault-${{ parameters.environment }}

stages:
  - stage: Seed_DB
    displayName: Seed ${{ parameters.environment }} Database
    jobs:
      - deployment: Seed_DB
        displayName: Seed Database
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - checkout: self
                - script: |
                    npm ci
                  displayName: Install dependencies
                  workingDirectory: $(Build.Repository.LocalPath)
                - script: echo "##vso[task.setvariable variable=DATABASE_URL]$(back-office-sql-connection-string)"
                  displayName: Set DATABASE_URL variable
                - script: npm run build
                  displayName: Build
                  workingDirectory: $(Build.Repository.LocalPath)/apps/api
                - script: |
                    npm run db:reset
                  displayName: Seed Database
                  workingDirectory: $(Build.Repository.LocalPath)/apps/api
        workspace:
          clean: all
