BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[S51Advice] DROP CONSTRAINT [S51Advice_redactedStatus_df];
ALTER TABLE [dbo].[S51Advice] ALTER COLUMN [redactedStatus] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
