const seeder = {
  up: (queryInterface) =>
    queryInterface.bulkInsert('LookUpLPA', [
      {
        LPA19Code: 'E60000001',
        LPA19Name: 'County Durham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000002',
        LPA19Name: 'Darlington',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000003',
        LPA19Name: 'Hartlepool',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000004',
        LPA19Name: 'Middlesbrough',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000005',
        LPA19Name: 'Northumberland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000006',
        LPA19Name: 'Redcar and Cleveland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000007',
        LPA19Name: 'Stockton-on-Tees',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000008',
        LPA19Name: 'Gateshead',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000009',
        LPA19Name: 'Newcastle upon Tyne',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000010',
        LPA19Name: 'North Tyneside',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000011',
        LPA19Name: 'South Tyneside',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000012',
        LPA19Name: 'Sunderland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000013',
        LPA19Name: 'Blackburn with Darwen',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000014',
        LPA19Name: 'Blackpool',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000015',
        LPA19Name: 'Cheshire East',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000016',
        LPA19Name: 'Cheshire West and Chester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000017',
        LPA19Name: 'Halton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000018',
        LPA19Name: 'Warrington',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000019',
        LPA19Name: 'Allerdale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000020',
        LPA19Name: 'Barrow-in-Furness',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000021',
        LPA19Name: 'Carlisle',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000022',
        LPA19Name: 'Copeland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000023',
        LPA19Name: 'Eden',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000024',
        LPA19Name: 'South Lakeland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000025',
        LPA19Name: 'Bolton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000026',
        LPA19Name: 'Bury',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000027',
        LPA19Name: 'Manchester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000028',
        LPA19Name: 'Oldham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000029',
        LPA19Name: 'Rochdale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000030',
        LPA19Name: 'Salford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000031',
        LPA19Name: 'Stockport',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000032',
        LPA19Name: 'Tameside',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000033',
        LPA19Name: 'Trafford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000034',
        LPA19Name: 'Wigan',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000035',
        LPA19Name: 'Burnley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000036',
        LPA19Name: 'Chorley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000037',
        LPA19Name: 'Fylde',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000038',
        LPA19Name: 'Hyndburn',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000039',
        LPA19Name: 'Lancaster',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000040',
        LPA19Name: 'Pendle',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000041',
        LPA19Name: 'Preston',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000042',
        LPA19Name: 'Ribble Valley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000043',
        LPA19Name: 'Rossendale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000044',
        LPA19Name: 'South Ribble',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000045',
        LPA19Name: 'West Lancashire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000046',
        LPA19Name: 'Wyre',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000047',
        LPA19Name: 'Knowsley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000048',
        LPA19Name: 'Liverpool',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000049',
        LPA19Name: 'Sefton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000050',
        LPA19Name: 'St. Helens',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000051',
        LPA19Name: 'Wirral',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000052',
        LPA19Name: 'East Riding of Yorkshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000053',
        LPA19Name: 'Kingston upon Hull, City of',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000054',
        LPA19Name: 'North East Lincolnshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000055',
        LPA19Name: 'North Lincolnshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000056',
        LPA19Name: 'York',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000057',
        LPA19Name: 'Craven',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000058',
        LPA19Name: 'Hambleton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000059',
        LPA19Name: 'Harrogate',
        Email: 'planning.appeals@harrogate.gov.uk',
        Domain: 'harrogate.gov.uk',
        InTrial: 1,
      },
      {
        LPA19Code: 'E60000060',
        LPA19Name: 'Richmondshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000061',
        LPA19Name: 'Ryedale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000062',
        LPA19Name: 'Scarborough',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000063',
        LPA19Name: 'Selby',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000064',
        LPA19Name: 'Barnsley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000065',
        LPA19Name: 'Doncaster',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000066',
        LPA19Name: 'Rotherham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000067',
        LPA19Name: 'Sheffield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000068',
        LPA19Name: 'Bradford',
        Email: 'appealsplanning@bradford.gov.uk',
        Domain: 'bradford.gov.uk',
        InTrial: 1,
      },
      {
        LPA19Code: 'E60000069',
        LPA19Name: 'Calderdale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000070',
        LPA19Name: 'Kirklees',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000071',
        LPA19Name: 'Leeds',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000072',
        LPA19Name: 'Wakefield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000073',
        LPA19Name: 'Derby',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000074',
        LPA19Name: 'Leicester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000075',
        LPA19Name: 'Nottingham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000076',
        LPA19Name: 'Rutland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000077',
        LPA19Name: 'Amber Valley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000078',
        LPA19Name: 'Bolsover',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000079',
        LPA19Name: 'Chesterfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000080',
        LPA19Name: 'Derbyshire Dales',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000081',
        LPA19Name: 'Erewash',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000082',
        LPA19Name: 'High Peak',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000083',
        LPA19Name: 'North East Derbyshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000084',
        LPA19Name: 'South Derbyshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000085',
        LPA19Name: 'Blaby',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000086',
        LPA19Name: 'Charnwood',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000087',
        LPA19Name: 'Harborough',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000088',
        LPA19Name: 'Hinckley and Bosworth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000089',
        LPA19Name: 'Melton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000090',
        LPA19Name: 'North West Leicestershire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000091',
        LPA19Name: 'Oadby and Wigston',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000092',
        LPA19Name: 'Boston',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000093',
        LPA19Name: 'East Lindsey',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000094',
        LPA19Name: 'Lincoln',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000095',
        LPA19Name: 'North Kesteven',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000096',
        LPA19Name: 'South Holland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000097',
        LPA19Name: 'South Kesteven',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000098',
        LPA19Name: 'West Lindsey',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000106',
        LPA19Name: 'Ashfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000107',
        LPA19Name: 'Bassetlaw',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000108',
        LPA19Name: 'Broxtowe',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000109',
        LPA19Name: 'Gedling',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000110',
        LPA19Name: 'Mansfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000111',
        LPA19Name: 'Newark and Sherwood',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000112',
        LPA19Name: 'Rushcliffe',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000113',
        LPA19Name: 'Herefordshire, County of',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000114',
        LPA19Name: 'Shropshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000115',
        LPA19Name: 'Stoke-on-Trent',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000116',
        LPA19Name: 'Telford and Wrekin',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000117',
        LPA19Name: 'Cannock Chase',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000118',
        LPA19Name: 'East Staffordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000119',
        LPA19Name: 'Lichfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000120',
        LPA19Name: 'Newcastle-under-Lyme',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000121',
        LPA19Name: 'South Staffordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000122',
        LPA19Name: 'Stafford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000123',
        LPA19Name: 'Staffordshire Moorlands',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000124',
        LPA19Name: 'Tamworth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000125',
        LPA19Name: 'North Warwickshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000126',
        LPA19Name: 'Nuneaton and Bedworth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000127',
        LPA19Name: 'Rugby',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000128',
        LPA19Name: 'Stratford-on-Avon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000129',
        LPA19Name: 'Warwick',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000130',
        LPA19Name: 'Birmingham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000131',
        LPA19Name: 'Coventry',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000132',
        LPA19Name: 'Dudley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000133',
        LPA19Name: 'Sandwell',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000134',
        LPA19Name: 'Solihull',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000135',
        LPA19Name: 'Walsall',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000136',
        LPA19Name: 'Wolverhampton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000137',
        LPA19Name: 'Bromsgrove',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000138',
        LPA19Name: 'Malvern Hills',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000139',
        LPA19Name: 'Redditch',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000140',
        LPA19Name: 'Worcester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000141',
        LPA19Name: 'Wychavon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000142',
        LPA19Name: 'Wyre Forest',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000143',
        LPA19Name: 'Bedford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000144',
        LPA19Name: 'Central Bedfordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000145',
        LPA19Name: 'Luton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000146',
        LPA19Name: 'Peterborough',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000147',
        LPA19Name: 'Southend-on-Sea',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000148',
        LPA19Name: 'Thurrock',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000149',
        LPA19Name: 'Cambridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000150',
        LPA19Name: 'East Cambridgeshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000151',
        LPA19Name: 'Fenland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000152',
        LPA19Name: 'Huntingdonshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000153',
        LPA19Name: 'South Cambridgeshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000154',
        LPA19Name: 'Basildon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000155',
        LPA19Name: 'Braintree',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000156',
        LPA19Name: 'Brentwood',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000157',
        LPA19Name: 'Castle Point',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000158',
        LPA19Name: 'Chelmsford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000159',
        LPA19Name: 'Colchester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000160',
        LPA19Name: 'Epping Forest',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000161',
        LPA19Name: 'Harlow',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000162',
        LPA19Name: 'Maldon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000163',
        LPA19Name: 'Rochford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000164',
        LPA19Name: 'Tendring',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000165',
        LPA19Name: 'Uttlesford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000166',
        LPA19Name: 'Broxbourne',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000167',
        LPA19Name: 'Dacorum',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000168',
        LPA19Name: 'East Hertfordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000169',
        LPA19Name: 'Hertsmere',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000170',
        LPA19Name: 'North Hertfordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000171',
        LPA19Name: 'St Albans',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000172',
        LPA19Name: 'Stevenage',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000173',
        LPA19Name: 'Three Rivers',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000174',
        LPA19Name: 'Watford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000175',
        LPA19Name: 'Welwyn Hatfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000176',
        LPA19Name: 'Breckland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000177',
        LPA19Name: 'Broadland',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000178',
        LPA19Name: 'Great Yarmouth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000179',
        LPA19Name: "King's Lynn and West Norfolk",
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000180',
        LPA19Name: 'North Norfolk',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000181',
        LPA19Name: 'Norwich',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000182',
        LPA19Name: 'South Norfolk',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000183',
        LPA19Name: 'Babergh',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000184',
        LPA19Name: 'East Suffolk',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000185',
        LPA19Name: 'Ipswich',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000186',
        LPA19Name: 'Mid Suffolk',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000187',
        LPA19Name: 'West Suffolk',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000188',
        LPA19Name: 'Camden',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000189',
        LPA19Name: 'City of London',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000190',
        LPA19Name: 'Hackney',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000191',
        LPA19Name: 'Hammersmith and Fulham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000192',
        LPA19Name: 'Haringey',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000193',
        LPA19Name: 'Islington',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000194',
        LPA19Name: 'Kensington and Chelsea',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000195',
        LPA19Name: 'Lambeth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000196',
        LPA19Name: 'Lewisham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000197',
        LPA19Name: 'Newham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000198',
        LPA19Name: 'Southwark',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000199',
        LPA19Name: 'Tower Hamlets',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000200',
        LPA19Name: 'Wandsworth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000201',
        LPA19Name: 'Westminster',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000202',
        LPA19Name: 'Barking and Dagenham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000203',
        LPA19Name: 'Barnet',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000204',
        LPA19Name: 'Bexley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000205',
        LPA19Name: 'Brent',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000206',
        LPA19Name: 'Bromley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000207',
        LPA19Name: 'Croydon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000208',
        LPA19Name: 'Ealing',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000209',
        LPA19Name: 'Enfield',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000210',
        LPA19Name: 'Greenwich',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000211',
        LPA19Name: 'Harrow',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000212',
        LPA19Name: 'Havering',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000213',
        LPA19Name: 'Hillingdon',
        Email: 'PlanningAppeals@Hillingdon.gov.uk',
        Domain: 'Hillingdon.gov.uk',
        InTrial: 1,
      },
      {
        LPA19Code: 'E60000214',
        LPA19Name: 'Hounslow',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000215',
        LPA19Name: 'Kingston upon Thames',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000216',
        LPA19Name: 'Merton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000217',
        LPA19Name: 'Redbridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000218',
        LPA19Name: 'Richmond upon Thames',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000219',
        LPA19Name: 'Sutton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000220',
        LPA19Name: 'Waltham Forest',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000221',
        LPA19Name: 'Bracknell Forest',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000222',
        LPA19Name: 'Brighton and Hove',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000223',
        LPA19Name: 'Isle of Wight',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000224',
        LPA19Name: 'Medway',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000225',
        LPA19Name: 'Milton Keynes',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000226',
        LPA19Name: 'Portsmouth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000227',
        LPA19Name: 'Reading',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000228',
        LPA19Name: 'Slough',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000229',
        LPA19Name: 'Southampton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000230',
        LPA19Name: 'West Berkshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000231',
        LPA19Name: 'Windsor and Maidenhead',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000232',
        LPA19Name: 'Wokingham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000237',
        LPA19Name: 'Eastbourne',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000238',
        LPA19Name: 'Hastings',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000239',
        LPA19Name: 'Lewes',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000240',
        LPA19Name: 'Rother',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000241',
        LPA19Name: 'Wealden',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000242',
        LPA19Name: 'Basingstoke and Deane',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000243',
        LPA19Name: 'East Hampshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000244',
        LPA19Name: 'Eastleigh',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000245',
        LPA19Name: 'Fareham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000246',
        LPA19Name: 'Gosport',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000247',
        LPA19Name: 'Hart',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000248',
        LPA19Name: 'Havant',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000249',
        LPA19Name: 'New Forest',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000250',
        LPA19Name: 'Rushmoor',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000251',
        LPA19Name: 'Test Valley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000252',
        LPA19Name: 'Winchester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000253',
        LPA19Name: 'Ashford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000254',
        LPA19Name: 'Canterbury',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000255',
        LPA19Name: 'Dartford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000256',
        LPA19Name: 'Dover',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000257',
        LPA19Name: 'Folkestone and Hythe',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000258',
        LPA19Name: 'Gravesham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000259',
        LPA19Name: 'Maidstone',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000260',
        LPA19Name: 'Sevenoaks',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000261',
        LPA19Name: 'Swale',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000262',
        LPA19Name: 'Thanet',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000263',
        LPA19Name: 'Tonbridge and Malling',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000264',
        LPA19Name: 'Tunbridge Wells',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000265',
        LPA19Name: 'Cherwell',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000266',
        LPA19Name: 'Oxford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000267',
        LPA19Name: 'South Oxfordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000268',
        LPA19Name: 'Vale of White Horse',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000269',
        LPA19Name: 'West Oxfordshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000270',
        LPA19Name: 'Elmbridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000271',
        LPA19Name: 'Epsom and Ewell',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000272',
        LPA19Name: 'Guildford',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000273',
        LPA19Name: 'Mole Valley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000274',
        LPA19Name: 'Reigate and Banstead',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000275',
        LPA19Name: 'Runnymede',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000276',
        LPA19Name: 'Spelthorne',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000277',
        LPA19Name: 'Surrey Heath',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000278',
        LPA19Name: 'Tandridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000279',
        LPA19Name: 'Waverley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000280',
        LPA19Name: 'Woking',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000281',
        LPA19Name: 'Adur',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000282',
        LPA19Name: 'Arun',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000283',
        LPA19Name: 'Chichester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000284',
        LPA19Name: 'Crawley',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000285',
        LPA19Name: 'Horsham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000286',
        LPA19Name: 'Mid Sussex',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000287',
        LPA19Name: 'Worthing',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000288',
        LPA19Name: 'Bath and North East Somerset',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000289',
        LPA19Name: 'Bournemouth, Christchurch and Poole',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000290',
        LPA19Name: 'Bristol, City of',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000291',
        LPA19Name: 'Cornwall',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000292',
        LPA19Name: 'Dorset',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000293',
        LPA19Name: 'Isles of Scilly',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000294',
        LPA19Name: 'North Somerset',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000295',
        LPA19Name: 'Plymouth',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000296',
        LPA19Name: 'South Gloucestershire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000297',
        LPA19Name: 'Swindon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000298',
        LPA19Name: 'Torbay',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000299',
        LPA19Name: 'Wiltshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000300',
        LPA19Name: 'East Devon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000301',
        LPA19Name: 'Exeter',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000302',
        LPA19Name: 'Mid Devon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000303',
        LPA19Name: 'North Devon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000304',
        LPA19Name: 'South Hams',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000305',
        LPA19Name: 'Teignbridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000306',
        LPA19Name: 'Torridge',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000307',
        LPA19Name: 'West Devon',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000308',
        LPA19Name: 'Cheltenham',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000309',
        LPA19Name: 'Cotswold',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000310',
        LPA19Name: 'Forest of Dean',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000311',
        LPA19Name: 'Gloucester',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000312',
        LPA19Name: 'Stroud',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000313',
        LPA19Name: 'Tewkesbury',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000314',
        LPA19Name: 'Mendip',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000315',
        LPA19Name: 'Sedgemoor',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000316',
        LPA19Name: 'Somerset West and Taunton',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000317',
        LPA19Name: 'South Somerset',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000318',
        LPA19Name: 'Dartmoor National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000319',
        LPA19Name: 'Exmoor National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000320',
        LPA19Name: 'Lake District National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000321',
        LPA19Name: 'New Forest National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000322',
        LPA19Name: 'North York Moors National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000323',
        LPA19Name: 'Northumberland National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000324',
        LPA19Name: 'Peak District National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000325',
        LPA19Name: 'South Downs National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000326',
        LPA19Name: 'The Broads Authority',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000327',
        LPA19Name: 'Yorkshire Dales National Park',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000328',
        LPA19Name: 'Ebbsfleet Development Corporation',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000329',
        LPA19Name: 'London Legacy Development Corporation',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000330',
        LPA19Name: 'Old Oak and Park Royal Development Corporation',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000331',
        LPA19Name: 'Buckinghamshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000332',
        LPA19Name: 'North Northamptonshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E60000333',
        LPA19Name: 'West Northamptonshire',
        Email: null,
        Domain: null,
        InTrial: 0,
      },
      {
        LPA19Code: 'E69999999',
        LPA19Name: 'System Test Borough Council',
        Email: 'AppealPlanningDecisionTest@planninginspectorate.gov.uk',
        Domain: 'planninginspectorate.gov.uk',
        InTrial: 1,
      },
    ]),
  down: (queryInterface) => queryInterface.bulkDelete('LookUpLPA', null, {}),
};

module.exports = seeder;
