const views = {
  appealAlreadyReviewed: 'appeal-already-reviewed',
  questionnaireAlreadyReviewed: 'questionnaire-already-reviewed',
  appealsList: 'appeals-list',
  questionnairesList: 'questionnaires-list',
  document: 'document',
  home: '',
  reviewAppealSubmission: 'review-appeal-submission',
  appealDetails: 'appeal-details',
  validAppealDetails: 'valid-appeal-details',
  invalidAppealDetails: 'invalid-appeal-details',
  missingOrWrong: 'missing-or-wrong',
  checkAndConfirm: 'check-and-confirm',
  reviewComplete: 'review-complete',
  reviewQuestionnaireComplete: 'review-questionnaire-complete',
  questionnairesForReview: 'questionnaires-for-review',
  reviewQuestionnaireSubmission: 'review-questionnaire-submission',
  questionnairecheckAndConfirm: 'questionnaire-check-and-confirm',
  search: 'search',
  searchResults: 'search-results',
  appellant: 'appeal-details/appellant',
  applicationDecisionDate: 'appeal-details/application-decision-date',
  caseOfficer: 'appeal-details/case-officer',
};

module.exports = views;
