BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[S51Advice] (
    [id] INT NOT NULL IDENTITY(1,1),
    [caseId] INT NOT NULL,
    [title] NVARCHAR(1000) NOT NULL,
    [enquirer] NVARCHAR(1000) NOT NULL,
    [enquiryMethod] NVARCHAR(1000) NOT NULL,
    [enquiryDate] DATETIME2 NOT NULL,
    [enquiryDetails] NVARCHAR(1000) NOT NULL,
    [adviser] NVARCHAR(1000) NOT NULL,
    [adviceDate] DATETIME2 NOT NULL,
    [adviceDetails] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [S51Advice_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL CONSTRAINT [S51Advice_updatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [S51Advice_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[S51Advice] ADD CONSTRAINT [S51Advice_caseId_fkey] FOREIGN KEY ([caseId]) REFERENCES [dbo].[Case]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
