BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
-- 	DO NOTHING: SEE TICKET https://pins-ds.atlassian.net/browse/BOAS-1576
-- ALTER TABLE [dbo].[ProjectTeam] ADD CONSTRAINT [ProjectTeam_caseId_fkey] FOREIGN KEY ([caseId]) REFERENCES [dbo].[Case]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
