BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[document] (
    [id] INT NOT NULL IDENTITY(1,1),
    [guid] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [folderId] INT NOT NULL,
    CONSTRAINT [document_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[document] ADD CONSTRAINT [document_folderId_fkey] FOREIGN KEY ([folderId]) REFERENCES [dbo].[Folder]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
