version: '3.7'

services:
  azure-sql-edge_migration-testing:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge_migration-testing
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'test-db-PASSWORD-123'
      MSSQL_PID: 'Developer'
    hostname: mssqlserver

  mssql-tools_migration-testing:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql-tools_migration-testing
    tty: true
    depends_on:
      - azure-sql-edge_migration-testing
    entrypoint: '/bin/bash'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "./opt/mssql-tools/bin/sqlcmd -S mssqlserver -U sa -P 'test-db-PASSWORD-123' -Q 'SELECT 1' || exit 1"
        ]
      interval: 5s
      retries: 5
      start_period: 150s

  back-office-api_migration-testing:
    image: node:20-alpine
    container_name: back-office-api_migration-testing
    environment:
      NODE_ENV: 'development'
      PORT: 3001
      DATABASE_URL: sqlserver://mssqlserver:1433;database=pins_development;user=sa;password=test-db-PASSWORD-123;trustServerCertificate=true
    ports:
      - '3001:3001'
    working_dir: /opt/app
    volumes:
      - ../../../../package.json:/opt/app/package.json
      - ../../../../node_modules:/opt/app/node_modules
      - ../../../../apps/api:/opt/app/apps/api
      - ../../../../packages:/opt/app/packages
    command: sh -c "npm run db:migrate --workspace=@pins/applications.api && npm run api"
    depends_on:
      mssql-tools_migration-testing:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 3001 || exit 1']
      interval: 5s
      retries: 10
      start_period: 300s

  applications-migration-functions_migration-testing:
    image: node:20-alpine
    container_name: applications-migration-functions_migration-testing
    environment:
      API_HOST: 'back-office-api_migration-testing:3001'
      BLOB_STORAGE_ACCOUNT_CUSTOM_DOMAIN: 'test-blob-store-domain'
      NODE_ENV: 'development'
    working_dir: /opt/app
    volumes:
      - ../../../../package.json:/opt/app/package.json
      - ../../../../node_modules:/opt/app/node_modules
      - ../../../../packages:/opt/app/packages
      - ../:/opt/app/apps/functions/applications-migration
    command: sh -c "npm run test:entry --workspace=@pins/functions-applications-migration"
    depends_on:
      back-office-api_migration-testing:
        condition: service_healthy
