BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[AppellantCase] ALTER COLUMN [otherNotValidReasons] NVARCHAR(4000) NULL;

-- AlterTable
ALTER TABLE [dbo].[LPAQuestionnaire] ALTER COLUMN [otherNotValidReasons] NVARCHAR(4000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
