BEGIN TRY

BEGIN TRAN;

-- Add the new seeds for the identity columns to 100 million
DBCC CHECKIDENT ('dbo.Case', RESEED, 100000000);
DBCC CHECKIDENT ('dbo.ApplicationDetails', RESEED, 100000000);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
